basic.showString("Hello!")
basic.showString("Welcome to Measuring Distance")
basic.showIcon(IconNames.Happy)
basic.pause(100)
basic.showIcon(IconNames.Umbrella)
basic.pause(100)
basic.showIcon(IconNames.Scissors)
basic.showString("Let's Start")
basic.pause(100)
basic.showString("3")
basic.pause(100)
basic.showString("2")
basic.pause(100)
basic.showString("1")
basic.forever(function () {
    basic.showNumber(Tinybit.Ultrasonic_Car())
})
